const initialState = {
  quote:[
    "If life were predictable it would cease to be life and be without flavor.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is a succession of lessons which must be lived to be understood.",
    "You will face many defeats in life, but never let yourself be defeated.",
    "Never let the fear of striking out keep you from playing the game.",
    "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
    "The only impossible journey is the one you never begin.",
    "In this life we cannot do great things. We can only do small things with great love.",
    "Only a life lived for others is a life worthwhile.",
    "The purpose of our lives is to be happy.",
    "Life is what happens when you're busy making other plans.",
    "You only live once, but if you do it right, once is enough.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Go confidently in the direction of your dreams! Live the life you've imagined.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Life is really simple, but we insist on making it complicated.",
    "May you live all the days of your life.",
    "Life itself is the most wonderful fairy tale.",
    "Do not let making a living prevent you from making a life.",
    "Life is ours to be spent, not to be saved.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Life is a long lesson in humility.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Love the life you live. Live the life you love.",
    "Life is either a daring adventure or nothing at all.",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    "Life is made of ever so many partings welded together.",
    "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma -- which is living with the results of other people's thinking.",
    "Life is trying things to see if they work.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up."
  ],
  author: [
    "Eleanor Roosevelt",
    "Abraham Lincoln",
    "Ralph Waldo Emerson",
    "Maya Angelou",
    "Babe Ruth",
    "Oscar Wilde",
    "Tony Robbins",
    "Mother Teresa",
    "Albert Einstein",
    "Dalai Lama",
    "John Lennon",
    "Mae West",
    "Ralph Waldo Emerson",
    "Henry David Thoreau",
    "Nelson Mandela",
    "Confucius",
    "Jonathan Swift",
    "Hans Christian Andersen",
    "John Wooden",
    "D. H. Lawrence",
    "Marilyn Monroe",
    "James M. Barrie",
    "Robert Frost",
    "Bob Marley",
    "Helen Keller",
    "Dr. Seuss",
    "Charles Dickens",
    "Steve Jobs",
    "Ray Bradbury",
    "Thomas A. Edison"
  ],
  index: 0
}

export default initialState;
